name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '12'

      - name: Install dependencies
        run: pip install -r requirements.txt || echo "No hay dependencias"

      - name: Run tests
        run: python -m unittest discover
